# Generated by Django 5.1 on 2024-08-26 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
        ('todolist', '0002_todoitem_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='contacts.contact'),
        ),
    ]
