# Generated by Django 5.0.7 on 2024-08-04 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_todoitem_description_todoitem_priority_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='priority',
        ),
        migrations.AddField(
            model_name='todoitem',
            name='tags',
            field=models.CharField(choices=[('yellow', 'Yellow'), ('blue', 'Blue'), ('green', 'Green')], default='medium', max_length=6),
        ),
    ]
