# Generated by Django 5.0.7 on 2024-08-04 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0004_todoitem_tasktype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='taskType',
            field=models.CharField(choices=[('todo', 'To-do'), ('doToday', 'Do today'), ('inProgress', 'In progress'), ('done', 'Done')], default='todo', max_length=10),
        ),
    ]
